name: Check Approved Reviews

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-approval:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Check if PR has approved reviews
        id: check_reviews
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });

            const approvedReview = reviews.find(review => review.state === 'APPROVED');

            if (!approvedReview) {
              core.setFailed('Pull request has no approved reviews.');
            }

      - name: Fail if no approvals
        run: echo "No approved reviews found. You need at least one approval before merging."
        if: failure() # This ensures the step runs only if the previous step failed
